alias adbq="./_scripts/go-scripts/adbq.sh"
alias bai="./build-and-install.sh"
alias baie="bai --som-id=emulator-5554 --tablet-id=emulator-5554 --build-type=so"
alias override="./_scripts/go-scripts/override.sh"
alias overridee="override --som-id=emulator-5554"
