#!/bin/bash

git log --pretty=format:"%H %ad" --author-date-order --date=unix | awk '
    BEGIN {
      i = 0;
    }

    {
      hashes[i] = $1
      timestamps[i] = $2;
      i += 1;
    }

    END {
      j = length(timestamps)
      for (i = 0; i < j - 1; i++) {
        if (timestamps[i] < timestamps[i + 1]) {
          printf("%s -> %s, %s -> %s\n",
                 hashes[i + 1], hashes[i],
                 strftime("%Y/%m/%d %H:%M:%S %Z", timestamps[i + 1], 1),
                 strftime("%Y/%m/%d %H:%M:%S %Z", timestamps[i], 1));
        }
      }
    }'
