#!/bin/bash

remote=$1
remoteBranch=$2
test -z "$remote" \
    && echo "ERROR: Please provide the source remote." 1>&2 \
    && exit 1
test -z "$remoteBranch" \
    && echo "ERROR: Please provide the source remote branch." 1>&2 \
    && exit 1

if currentBranch=$(git symbolic-ref --short -q HEAD)
then
    echo On branch "$currentBranch"
    echo "Pulling updates from the $remote branch $remoteBranch ..."

    # Fetch changes
    git fetch --prune --tags --force "$remote"
    # Stash current changes
    git stash
    # Checkout remote branch from where you want to update.
    git checkout "$remoteBranch"
    # Pull the branch to update it
    git pull --rebase "$remote" "$remoteBranch"
    # Remove deleted branches
    git rmbr
    # Checkout current branch which you were on before.
    git checkout "$currentBranch"
    # Rebase the changes
    git rebase "$remoteBranch"
    # Apply the stashed changes
    git stash apply

    echo "Updated the $currentBranch with changes from $remoteBranch"
else
    echo "ERROR: Cannot find the current branch!"
fi
