#!/bin/sh

remote=$1
remoteBranch=$2
test -z "$remote" \
    && echo "ERROR: Please provide the source remote." 1>&2 \
    && exit 1
test -z "$remoteBranch" \
    && echo "ERROR: Please provide the source remote." 1>&2 \
    && exit 1

git fetch --prune --tags --force "$remote"
git checkout "$remoteBranch"
git pull --rebase "$remote" "$remoteBranch"
git rmbr
