nnoremap <silent><buffer><expr> <ESC> denite#do_map('quit')
nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
nnoremap <silent><buffer><expr> s denite#do_map('do_action', 'vsplit')
nnoremap <silent><buffer><expr> t denite#do_map('do_action', 'tabopen')
nnoremap <silent><buffer><expr> r denite#do_map('redraw')
nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <C-o> denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <Tab> denite#do_map('choose_action')
